### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/kprobes/blacklist'

### ISSUE THREAD

**Issue by EricHChz** [facebookexperimental/ExtendedAndroidTools#43]
When I use bcc tools, such as cachestat, python3 cachestat -T

this error:
Traceback (most recent call last):
  File "/data/local/tmp/bpftools/share/bcc/tools/cachestat", line 104, in <module>
    if BPF.get_kprobe_functions(b'folio_account_dirtied'):
  File "/data/local/tmp/bpftools/lib/python3.10/site-packages/bcc/__init__.py", line 698, in get_kprobe_functions
    raise e
  File "/data/local/tmp/bpftools/lib/python3.10/site-packages/bcc/__init__.py", line 694, in get_kprobe_functions
    with open(blacklist_file, "rb") as blacklist_f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/kprobes/blacklist'

**Comment by EricHChz** [comment]
1、CONFIG_DEBUG_FS=y      find this config
2、mount -t debugfs none /sys/kernel/debug/
